env:
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  no-plusplus: 0
  no-bitwise: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    # - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
